name = "Mundo 1 - Vanilla+"
author = "ManoboCheyon"
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eddb078a5de39019ec0b6e089fdb8f233e0109b22d8c29a76072189007d5ae5d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
