name = "Mundo 1 - Vanilla+"
author = "ManoboCheyon"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d711d86fb4e52e14dc2321424cfcfaff2c25af10485fa82bbb7b14f339fb91c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
